apiVersion: apps/v1
kind: Deployment

metadata:
  name: wonderlust
  namespace: wonderlust-prod

spec:
  replicas: 3

  selector: 
    matchLabels:
      app: wonderlust-app

# This is the Pod blueprint. Whenever Kubernetes needs a new Pod:
  template:
    metadata:
      labels:
        app: wonderlust-app
        env: prod

    spec:
      containers:
      - name: wonderlusta-app
        image: shivamsdeng/wonderlust:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        envFrom:
          - configMapRef: 
              name: wonderlust-config
          - secretRef:
              name: wonderlust-secret
      
