apiVersion: v1
kind: Service

metadata:
  name: wonderlust-service
  namespace: wonderlust-ns

spec: 
  type: NodePort

  selector:
    app: wonderlust-app

  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080

